Repository US-EPA-CAMD/easey-emissions-api, pull requests merged in 2021-07, with the labels that each got.

#78 Release pipeline
  .github/workflows/release-branch.yml
  .github/workflows/staging-deployment.yml
  .github/workflows/test-deployment.yml
Labels: DevOps, Tech Team

#80 feature/79-Update-README-files-in-repos-with-disclaimer
  README.md
Labels: Tech Team

#81 Feature/1256 Validation for Ozone Season Emissions API
  src/dto/annual-apportioned-emissions.params.dto.ts
  src/dto/monthly-apportioned-emissions.params.dto.ts
  src/dto/ozone-apportioned-emissions.params.dto.ts
  src/dto/quarterly-apportioned-emissions.params.dto.ts
Labels: Datateers
