Repository US-EPA-CAMD/easey-emissions-api, pull requests merged in 2021-01, with the labels that each got.

#20 Feature/617 update emissions readme
  README.md
Labels: Datateers, documentation

#21 Feature/618 update orisCode validation to allow leading 0s
  src/dto/hourly-apportioned-emissions.params.dto.ts
  src/pipes/date-validation.pipe.ts
  src/pipes/is-oris-code.pipe.ts
  src/pipes/oris-code-validation.pipes.ts
  src/pipes/state-validation.pipe.ts
Labels: Datateers

#22 Bug/ 597 API Pagination
  src/hourly-apportioned-emissions/hourly-apportioned-emissions.service.spec.ts
  src/hourly-apportioned-emissions/hourly-apportioned-emissions.service.ts
Labels: Datateers

#23 Feature/ 572 control technology validation
  src/dto/hourly-apportioned-emissions.params.dto.ts
  src/entities/control-code.entity.ts
  src/enums/control-technology.enum.ts
  src/pipes/is-control-technology.pipe.ts
Labels: Datateers

#25 Feature/621 make dates required
  nest-cli.json
  package-lock.json
  package.json
  src/dto/hourly-apportioned-emissions.params.dto.ts
  src/hourly-apportioned-emissions/hourly-apportioned-emissions.service.spec.ts
  src/hourly-apportioned-emissions/hourly-apportioned-emissions.service.ts
  src/pipes/date-validation.pipe.ts
  src/pipes/is-date-greater.pipe.ts
  src/pipes/is-in-date-range.pipe.ts
  src/pipes/is-iso-format.pipe.ts
  src/pipes/is-valid-date.pipe.ts
Labels: Datateers

#26 Feature/595 unit fuel type validation
  src/dto/hourly-apportioned-emissions.params.dto.ts
  src/entities/fuel-type-code.entity.ts
  src/enums/unit-fuel-type.enum.ts
  src/pipes/is-unit-fuel-type.pipe.ts
Labels: Datateers

#27 Feature/594 validate unit type
  src/dto/hourly-apportioned-emissions.params.dto.ts
  src/entities/unit-type-code.entity.ts
  src/enums/unit-type.enum.ts
  src/pipes/is-unit-fuel-type.pipe.ts
  src/pipes/is-unit-type.pipe.ts
Labels: Datateers

#28 Feature/632 configure easey emmissions api unit tests
  .github/workflows/develop-branch.yml
  .github/workflows/feature-branch.yml
  .github/workflows/release-branch.yml
  package-lock.json
  package.json
  sonar-project.properties
  src/app.module.ts
  src/dto/hourly-apportioned-emissions.params.dto.ts
  src/hourly-apportioned-emissions/hourly-apportioned-emissions.controller.spec.ts
  src/hourly-apportioned-emissions/hourly-apportioned-emissions.controller.ts
  src/hourly-apportioned-emissions/hourly-apportioned-emissions.module.ts
  src/main.ts
  src/pipes/is-unit-type.pipe.ts
  src/routes.ts
  src/utils/response.headers.ts
  test-report.xml
Labels: DevOps, Tech Team

#29 feature/646 unit test coverage for emissions API
  .gitignore
  package-lock.json
  package.json
  src/dto/hourly-apportioned-emissions.params.dto.spec.ts
  src/hourly-apportioned-emissions/hour-unit-data.repository.spec.ts
  src/hourly-apportioned-emissions/hourly-apportioned-emissions.controller.spec.ts
  src/hourly-apportioned-emissions/hourly-apportioned-emissions.service.spec.ts
  test-report.xml
Labels: Datateers, Testing
