Repository US-EPA-CAMD/easey-emissions-api, pull requests merged in 2022-02, with the labels that each got.

#107 Configure submission
  src/config/app.config.ts
  src/dto/emissions-submissions-response.dto.ts
  src/dto/emissions-submissions.params.dto.ts
  src/emissions/emissions.controller.spec.ts
  src/emissions/emissions.controller.ts
  src/emissions/emissions.module.ts
  src/emissions/emissions.repository.ts
  src/emissions/emissions.service.spec.ts
  src/emissions/emissions.service.ts
Labels: Emissioners, Tech Team

#111 Emission-Config
  manifest.yml
  src/config/app.config.ts
  src/emissions/emissions.repository.ts
  src/emissions/emissions.service.ts
Labels: Datateers, Tech Team

#113 Feature/2447-Refactor-Error-Message-Links
  package.json
  yarn.lock
Labels: Datateers

#114 Feature/2495-Address-Data-Inconsistencies-With-Compliance-Allowance-Based-Data
  package.json
  yarn.lock
Labels: Datateers

#118 Bug/2651 error message link
  package.json
  yarn.lock
Labels: Datateers

#122 Feature/2632 Create MATS Data Streaming Endpoint
  package.json
  src/apportioned-emissions/mats/hourly/hour-unit-mats-data.repository.spec.ts
  src/apportioned-emissions/mats/hourly/hour-unit-mats-data.repository.ts
  src/apportioned-emissions/mats/hourly/hourly-mats-apportioned-emissions.controller.spec.ts
  src/apportioned-emissions/mats/hourly/hourly-mats-apportioned-emissions.controller.ts
  src/apportioned-emissions/mats/hourly/hourly-mats-apportioned-emissions.service.spec.ts
  src/apportioned-emissions/mats/hourly/hourly-mats-apportioned-emissions.service.ts
  src/constants/field-mappings.ts
  yarn.lock
Labels: Datateers

#123 Bug/2708 Emissions API endpoints fuel type filter not working
  src/utils/query-builder.helper.ts
Labels: Datateers

#121 Feature/2633 mats filter logic
  src/apportioned-emissions/mats/hourly/hour-unit-mats-data.repository.ts
  src/apportioned-emissions/mats/mats-apportioned-emissions.controller.spec.ts
  src/apportioned-emissions/mats/mats-apportioned-emissions.controller.ts
  src/apportioned-emissions/mats/mats-apportioned-emissions.module.ts
  src/apportioned-emissions/mats/mats-apportioned-emissions.service.spec.ts
  src/apportioned-emissions/mats/mats-apportioned-emissions.service.ts
  src/dto/applicable-mats-apportioned-emissions-attributes-params.dto.ts
  src/dto/applicable-mats-apportioned-emissions-attributes.dto.ts
  src/entities/control-year-dim.entity.ts
  src/entities/fuel-year-dim.entity.ts
  src/entities/hour-unit-mats-data-arch.entity.ts
  src/entities/hour-unit-mats-data.entity.ts
  src/entities/unit-fact.entity.ts
  src/entities/unit-type-year-dim.entity.ts
  src/utils/validator.const.ts
Labels: Datateers

#124 Bug/2708 Emissions API endpoints fuel type filter not working
  src/utils/query-builder.helper.ts
Labels: Datateers
