Repository US-EPA-CAMD/easey-emissions-api, pull requests merged in 2022-07, with the labels that each got.

#170 Bug/3655 aggregation pagination endpoints returning 500 error when the system detects no results
  src/apportioned-emissions/annual/annual-unit-data.repository.ts
  src/apportioned-emissions/daily/day-unit-data.repository.spec.ts
  src/apportioned-emissions/daily/day-unit-data.repository.ts
  src/apportioned-emissions/hourly/hour-unit-data.repository.spec.ts
  src/apportioned-emissions/hourly/hour-unit-data.repository.ts
  src/apportioned-emissions/monthly/month-unit-data.repository.spec.ts
  src/apportioned-emissions/monthly/month-unit-data.repository.ts
  src/apportioned-emissions/quarterly/quarter-unit-data.repository.ts
Labels: Datateers

#172 feature/3453-Emissions-Submissions
  src/entities/emissions-submission-progress.entity.ts
Labels: Tech Team

#173 Bug/3842-Data-Preview-Not-Returning-Text-For-Emissions-Quarterly-State
  src/constants/field-mappings.ts
Labels: Datateers

#176 Feature/2786-Create-Quarterly-Emissions-National-Aggregation-Endpoints
  src/apportioned-emissions/quarterly/quarter-unit-data.repository.spec.ts
  src/apportioned-emissions/quarterly/quarter-unit-data.repository.ts
  src/apportioned-emissions/quarterly/quarterly-apportioned-emissions.controller.spec.ts
  src/apportioned-emissions/quarterly/quarterly-apportioned-emissions.controller.ts
  src/apportioned-emissions/quarterly/quarterly-apportioned-emissions.service.spec.ts
  src/apportioned-emissions/quarterly/quarterly-apportioned-emissions.service.ts
  src/constants/field-mappings.ts
  src/dto/quarterly-apportioned-emissions-national-aggregation.dto.ts
Labels: Datateers

#174 feature/3835 api define emissions entities 3
  src/entities/daily-emission.entity.ts
  src/entities/hrly-op-data.entity.ts
  src/entities/nsps4t-summary.entity.ts
  src/entities/summary-value.entity.ts
Labels: Emissioners

#177 feature/3837 API: Define Emissions Entities Schema #4
  src/entities/daily-fuel.entity.ts
  src/entities/daily-test-summary.entity.ts
  src/entities/derived-hrly-value.entity.ts
  src/entities/hrly-fuel-flow.entity.ts
  src/entities/hrly-gas-flow-meter.entity.ts
  src/entities/long-term-fuel-flow.entity.ts
  src/entities/mats-derived-hrly-value.entity.ts
  src/entities/mats-monitor-hrly-value.entity.ts
  src/entities/monitor-hrly-value.entity.ts
  src/entities/nsps4t-annual.entity.ts
  src/entities/nsps4t-compliance-period.entity.ts
  src/entities/sorbent-trap.entity.ts
  src/entities/weekly-test-summary.entity.ts
Labels: Emissioners

#178 feature/App-Name
  src/config/typeorm.config.ts
Labels: Tech Team

#179 Feature/2787-Create-Ozone-Emissions-Facility-Aggregation-Endpoints
  src/apportioned-emissions/ozone/ozone-apportioned-emissions.controller.spec.ts
  src/apportioned-emissions/ozone/ozone-apportioned-emissions.controller.ts
  src/apportioned-emissions/ozone/ozone-apportioned-emissions.service.spec.ts
  src/apportioned-emissions/ozone/ozone-apportioned-emissions.service.ts
  src/apportioned-emissions/ozone/ozone-unit-data.repository.spec.ts
  src/apportioned-emissions/ozone/ozone-unit-data.repository.ts
  src/constants/field-mappings.ts
  src/dto/ozone-apportioned-emissions-aggregation.dto.ts
  src/dto/ozone-apportioned-emissions-facility-aggregation.dto.ts
Labels: Datateers

#180 feature/Easey-Common-Exception
  package.json
  src/apportioned-emissions/annual/annual-apportioned-emissions.service.ts
  src/apportioned-emissions/apportioned-emissions.service.ts
  src/apportioned-emissions/daily/daily-apportioned-emissions.service.ts
  src/apportioned-emissions/hourly/hourly-apportioned-emissions.service.ts
  src/apportioned-emissions/mats/hourly/hourly-mats-apportioned-emissions.service.ts
  src/apportioned-emissions/mats/mats-apportioned-emissions.service.ts
  src/apportioned-emissions/monthly/monthly-apportioned-emissions.service.ts
  src/apportioned-emissions/ozone/ozone-apportioned-emissions.service.ts
  src/apportioned-emissions/quarterly/quarterly-apportioned-emissions.service.ts
  yarn.lock
Labels: Tech Team

#182 feature/3838: API: Define Emissions Entities Schema #5
  src/entities/daily-calibration.entity.ts
  src/entities/hrly-param-fuel-flow.entity.ts
  src/entities/sampling-train.entity.ts
  src/entities/weekly-system-integrity.entity.ts
Labels: Emissioners

#183 Feature/2788-Create-Ozone-Emissions-State-Aggregation-Endpoints
  src/apportioned-emissions/ozone/ozone-apportioned-emissions.controller.spec.ts
  src/apportioned-emissions/ozone/ozone-apportioned-emissions.controller.ts
  src/apportioned-emissions/ozone/ozone-apportioned-emissions.service.spec.ts
  src/apportioned-emissions/ozone/ozone-apportioned-emissions.service.ts
  src/apportioned-emissions/ozone/ozone-unit-data.repository.spec.ts
  src/apportioned-emissions/ozone/ozone-unit-data.repository.ts
  src/constants/field-mappings.ts
  src/dto/ozone-apportioned-emissions-state-aggregation.dto.ts
Labels: Datateers

#185 feature/Swagger-Desc
  package.json
  src/config/app.config.ts
  yarn.lock
Labels: Tech Team

#184 Feature/2789-Create-Ozone-Emissions-National-Aggregation-Endpoints
  src/apportioned-emissions/ozone/ozone-apportioned-emissions.controller.spec.ts
  src/apportioned-emissions/ozone/ozone-apportioned-emissions.controller.ts
  src/apportioned-emissions/ozone/ozone-apportioned-emissions.service.spec.ts
  src/apportioned-emissions/ozone/ozone-apportioned-emissions.service.ts
  src/apportioned-emissions/ozone/ozone-unit-data.repository.spec.ts
  src/apportioned-emissions/ozone/ozone-unit-data.repository.ts
  src/constants/field-mappings.ts
  src/dto/ozone-apportioned-emissions-national-aggregation.dto.ts
Labels: Datateers
