Repository US-EPA-CAMD/easey-emissions-api, pull requests merged in 2022-09, with the labels that each got.

#226 fix/import-38
  src/weekly-test-summary-workspace/weekly-test-summary-check.service.ts
Labels: Emissioners

#227 fix: Hourly operating export
  src/hourly-operating-workspace/hourly-operating.service.ts
  src/hourly-operating/hourly-operating.service.ts
Labels: Emissioners

#228 Bug/4043 Filter Daily Test Summary Data By Year and Quarter
  src/daily-test-summary-workspace/daily-test-summary.repository.ts
  src/daily-test-summary-workspace/daily-test-summary.service.ts
  src/daily-test-summary/daily-test-summary.repository.ts
  src/daily-test-summary/daily-test-summary.service.spec.ts
  src/daily-test-summary/daily-test-summary.service.ts
  src/emissions-workspace/emissions.service.ts
  src/emissions/emissions.service.ts
  yarn.lock
Labels: Datateers

#229 test/4076 increase unit test coverage for daily test module
  src/daily-calibration-workspace/daily-calibration.service.ts
  src/daily-calibration/daily-calibration.service.ts
  src/daily-test-summary-workspace/daily-test-summary.service.spec.ts
  src/daily-test-summary-workspace/daily-test-summary.service.ts
  src/daily-test-summary/daily-test-summary.service.spec.ts
  src/daily-test-summary/daily-test-summary.service.ts
  src/entities/workspace/monitor-location.entity.ts
  src/maps/daily-test-summary-map.spec.ts
  src/maps/daily-test-summary.map.ts
  test/mocks/mock-daily-calibration-repository.ts
  test/mocks/mock-daily-calibration-workspace-repository.ts
  test/mocks/mock-daily-test-summary-repository.ts
  test/mocks/mock-daily-test-summary-workspace-repository.ts
  test/object-generators/daily-calibration.ts
  test/object-generators/daily-test-summary.ts
  test/object-generators/derived-hourly-value.ts
  test/object-generators/monitor-location.ts
  test/object-generators/util.ts
Labels: Emissioners

#235 feature/Gateway-Token
  .github/workflows/develop-branch.yml
  .github/workflows/release-branch.yml
  package.json
Labels: Tech Team

#238 feature/Gateway-Token
  package.json
  yarn.lock
Labels: Tech Team

#241 feature/Converted-Bootstrap
  manifest.yml
  package.json
  src/config/app.config.ts
  src/main.ts
Labels: Tech Team

#256 Date range and date format bug fix
  src/dto/daily-calibration.dto.ts
  src/dto/daily-emission.dto.ts
  src/dto/daily-test-summary.dto.ts
  src/dto/emissions.dto.ts
  src/dto/hourly-operating.dto.ts
  src/dto/sorbent-trap.dto.ts
  src/dto/weekly-test-summary.dto.ts
  src/emissions-workspace/emissions-checks.service.ts
  src/emissions-workspace/emissions.controller.ts
  src/emissions-workspace/emissions.service.ts
  src/emissions/emissions.controller.ts
Labels: bug
