Repository US-EPA-CAMD/easey-emissions-api, pull requests merged in 2023-10, with the labels that each got.

#410 fix/Export
  src/hourly-fuel-flow/hourly-fuel-flow.repository.ts
  src/hourly-parameter-fuel-flow/hourly-parameter-fuel-flow.repository.ts
Labels: Tech Team

#419 Feature/5583 remove emissions endpoints
  src/derived-hourly-value-functions/derived-hourly-value-export.spec.ts
  src/derived-hourly-value-functions/derived-hourly-value-export.ts
  src/derived-hourly-value/derived-hourly-value.controller.spec.ts
  src/derived-hourly-value/derived-hourly-value.controller.ts
  src/derived-hourly-value/derived-hourly-value.module.ts
  src/derived-hourly-value/derived-hourly-value.service.spec.ts
  src/derived-hourly-value/derived-hourly-value.service.ts
  src/dto/derived-hourly-value-params.dto.spec.ts
  src/dto/derived-hourly-value-params.dto.ts
  src/dto/hourly-operating-params.dto.spec.ts
  src/dto/hourly-operating.params.dto.ts
  src/dto/summary-value-params.dto.spec.ts
  src/dto/summary-value-params.dto.ts
  src/hourly-operating-functions/hourly-operating-export.spec.ts
  src/hourly-operating-functions/hourly-operating-export.ts
  src/hourly-operating/hourly-operating.controller.spec.ts
  src/hourly-operating/hourly-operating.controller.ts
  src/hourly-operating/hourly-operating.module.ts
  src/hourly-operating/hourly-operating.service.spec.ts
  src/hourly-operating/hourly-operating.service.ts
  src/summary-value-functions/summary-value-export.spec.ts
  src/summary-value-functions/summary-value-export.ts
  src/summary-value/summary-value.controller.spec.ts
  src/summary-value/summary-value.controller.ts
  src/summary-value/summary-value.module.ts
  src/summary-value/summary-value.service.ts
  test/object-generators/derived-hourly-value.ts
  test/object-generators/hourly-operating-dto.ts
  test/object-generators/summary-value-dto.ts
Labels: ECMPS Prod Team

#421 Feature/5767 update emissions dto range validations
  package.json
  src/dto/daily-backstop.dto.ts
  src/dto/daily-calibration.dto.ts
  src/dto/daily-emission.dto.ts
  src/dto/daily-fuel.dto.ts
  src/dto/daily-test-summary.dto.ts
  src/dto/derived-hourly-value.dto.ts
  src/dto/emissions.dto.ts
  src/dto/hourly-fuel-flow.dto.ts
  src/dto/hourly-gas-flow-meter.dto.ts
  src/dto/hourly-operating.dto.ts
  src/dto/hourly-param-fuel-flow.dto.ts
  src/dto/long-term-fuel-flow.dto.ts
  src/dto/mats-monitor-hourly-value.dto.ts
  src/dto/monitor-hourly-value.dto.ts
  src/dto/nsps4t-annual.dto.ts
  src/dto/nsps4t-compliance-period.dto.ts
  src/dto/nsps4t-summary.dto.ts
  src/dto/sampling-train.dto.ts
  src/dto/sorbent-trap.dto.ts
  src/dto/summary-value.dto.ts
  src/dto/weekly-system-integrity.dto.ts
  src/dto/weekly-test-summary.dto.ts
  yarn.lock
Labels: Tech Team

#428 🐛Bug/5799: Emissions Data Export and Import from Historical
  src/config/app.config.ts
  src/hourly-operating-workspace/hourly-operating.service.ts
  src/hourly-operating/hourly-operating.service.ts
  src/utils/utils.ts
Labels: bug, ECMPS Prod Team

#431 Bug/5820-Modify-Emissions-Endpoints-To-Be-Consistent-With-Streaming-Endpoints
  src/constants/field-mappings.ts
  src/dto/hourly-apportioned-emissions.dto.ts
  src/entities/vw-hour-unit-data.entity.ts
Labels: Tech Team
